# Generated by Django 4.2 on 2023-06-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Agentliklar',
                'verbose_name_plural': 'Agentliklar',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('surname', models.CharField(max_length=100, verbose_name='Familya')),
                ('phone', models.CharField(max_length=15, verbose_name='Raqam')),
                ('tg_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id')),
            ],
            options={
                'verbose_name': 'Agentlar',
                'verbose_name_plural': 'Agentlar',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Proektlar',
                'verbose_name_plural': 'Proektlar',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('inn', models.CharField(max_length=50, verbose_name='INN')),
                ('code', models.CharField(max_length=50, verbose_name='Raqam')),
                ('status', models.BooleanField(default=False, verbose_name='Ahvoli')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.agency', verbose_name='Agentlik')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.agent', verbose_name='Agent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.project', verbose_name='Proekt')),
            ],
            options={
                'verbose_name': 'Kontraklar',
                'verbose_name_plural': 'Kontraklar',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgargan sana")),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='files', verbose_name='Fayl')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.project', verbose_name='Proekt')),
            ],
            options={
                'verbose_name': 'Sertifikatlar',
                'verbose_name_plural': 'Sertifikatlar',
            },
        ),
        migrations.AddField(
            model_name='agency',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support_app.agent', verbose_name='Agent'),
        ),
    ]
