# Generated by Django 4.2 on 2023-04-09 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agentliklar', 'verbose_name_plural': 'Agentliklar'},
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agentlar', 'verbose_name_plural': 'Agentlar'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Sertifikatlar', 'verbose_name_plural': 'Sertifikatlar'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Kontraklar', 'verbose_name_plural': 'Kontraklar'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proektlar', 'verbose_name_plural': 'Proektlar'},
        ),
    ]
