# Generated by Django 4.2 on 2023-04-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_alter_agency_options_alter_agent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='project',
        ),
        migrations.AddField(
            model_name='agent',
            name='project',
            field=models.ManyToManyField(to='support_app.project', verbose_name='Proekt'),
        ),
    ]
