# Generated by Django 4.2 on 2025-06-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_alter_agent_created_at_alter_agent_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='support_app.brand', verbose_name='Бренд'),
        ),
    ]
