# Generated by Django 4.2 on 2023-06-09 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0002_alter_agent_agency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counter',
            old_name='dat',
            new_name='day',
        ),
    ]
