# Generated by Django 4.2 on 2023-06-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0003_rename_dat_counter_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='agency',
        ),
    ]
