# Generated by Django 4.2 on 2025-06-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0003_alter_project_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'verbose_name': 'Счётчик для контрактов', 'verbose_name_plural': 'Счётчик для контрактов'},
        ),
        migrations.AlterField(
            model_name='counter',
            name='count',
            field=models.PositiveBigIntegerField(default=1, verbose_name='Счёт'),
        ),
    ]
