# Generated by Django 4.2 on 2023-04-09 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0003_remove_agent_project_agent_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='project',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='project',
        ),
        migrations.AddField(
            model_name='agency',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='support_app.agent', verbose_name='Agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='support_app.agent', verbose_name='Agent'),
            preserve_default=False,
        ),
    ]
