# Generated by Django 4.2 on 2025-06-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0004_alter_counter_options_alter_counter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Спец пдф'),
        ),
    ]
