# Generated by Django 4.2 on 2023-04-09 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0004_remove_agency_project_remove_agent_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='id',
        ),
        migrations.AlterField(
            model_name='agent',
            name='tg_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id'),
        ),
    ]
