# Generated by Django 4.2 on 2023-06-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0005_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='tg_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='day',
            field=models.PositiveIntegerField(default=13),
        ),
    ]
