# Generated by Django 4.2 on 2023-06-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0006_alter_agent_tg_id_alter_counter_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='agency',
        ),
        migrations.AlterField(
            model_name='counter',
            name='day',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AddField(
            model_name='agent',
            name='agency',
            field=models.ManyToManyField(to='support_app.agency', verbose_name='Agentlik'),
        ),
    ]
