# Generated by Django 4.2 on 2023-07-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0008_alter_project_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature',
            field=models.TextField(default=1, verbose_name='Hujjat turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='uniq',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Harf yoki soni'),
        ),
        migrations.AlterField(
            model_name='counter',
            name='day',
            field=models.PositiveIntegerField(default=11),
        ),
    ]
