# Generated by Django 4.2 on 2023-07-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0009_contract_signature_alter_agent_uniq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='signature',
        ),
        migrations.AddField(
            model_name='project',
            name='signature',
            field=models.TextField(default=1, verbose_name='Hujjat turi'),
            preserve_default=False,
        ),
    ]
