# Generated by Django 4.2 on 2023-07-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0011_alter_agent_uniq_alter_counter_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_boss',
            field=models.BooleanField(default=False, verbose_name="Qo'shimcha funktsional"),
        ),
        migrations.AlterField(
            model_name='counter',
            name='day',
            field=models.PositiveIntegerField(default=13),
        ),
        migrations.AlterField(
            model_name='project',
            name='uniq',
            field=models.CharField(max_length=100, verbose_name='Harf yoki soni'),
        ),
    ]
